import { describe, it, expect, vi } from "vitest";
import request from "supertest";
import { createApp } from "../src/app";
import { IntentClassifier } from "../src/services/ai/classifier/intent.classifier";
import { ToolExecutor } from "../src/services/ai/tools/tool.executor";
import { OrchestratorService } from "../src/services/ai/orchestrator.service";
import { GeminiAIProvider } from "../src/services/ai/providers/gemini.provider";
import { DeterministicAIProvider } from "../src/services/ai/providers/deterministic.provider";
import { AIProvider } from "../src/services/ai/providers/ai.provider";
import { TOOL_REGISTRY } from "../src/services/ai/tools/tool.registry";
import { TourismService } from "../src/services/tourism.service";
import { WeatherService } from "../src/services/external/weather/weather.service";
import { PreferencesService } from "../src/services/preferences.service";
import { AuthenticatedUser } from "../src/types/auth";
import { OrchestratorResponseDto } from "../src/types/ai";

describe("AI Orchestrator & Multi-Tool Coordination Suite (Phase 6A-6C)", () => {
  const app = createApp();

  describe("6A: AI Provider Abstraction", () => {
    it("should throw BadGatewayError if Gemini provider is invoked without an API key", async () => {
      const provider = new GeminiAIProvider("");
      await expect(provider.generateText("Hello")).rejects.toThrow(
        "GEMINI_API_KEY is not configured on the server"
      );
    });

    it("should generate deterministic structured output with DeterministicAIProvider", async () => {
      const provider = new DeterministicAIProvider();
      const mockPrompt = `Verified Context Data:
\`\`\`json
{
  "intent": "trip_planning",
  "destination": { "id": "123", "name": "Araku Valley", "state": "Andhra Pradesh" },
  "attractions": [{ "name": "Borra Caves", "description": "Historic limestone caves" }],
  "sources": [{ "type": "database", "provider": "Supabase", "resource": "destinations" }]
}
\`\`\``;

      const result = await provider.generateStructuredResponse<OrchestratorResponseDto>(mockPrompt);
      expect(result.intent).toBe("trip_planning");
      expect(result.destination?.name).toBe("Araku Valley");
      expect(result.recommendations.length).toBeGreaterThan(0);
      expect(result.recommendations[0].title).toBe("Borra Caves");
      expect(result.sources.length).toBe(1);
    });

    it("should use mock AI provider cleanly in orchestrator", async () => {
      const mockProvider: AIProvider = {
        providerName: "MockAI",
        generateStructuredResponse: vi.fn().mockResolvedValue({
          intent: "destination_information",
          summary: "Custom plan generated by mock AI",
          recommendations: [],
          warnings: [],
          sources: []
        }),
        generateText: vi.fn().mockResolvedValue("Mock text")
      };

      const mockExecutor = {
        executeTools: vi.fn().mockResolvedValue({
          destination: { name: "Tirupati" },
          sources: []
        })
      } as unknown as ToolExecutor;

      const orchestrator = new OrchestratorService(
        mockProvider,
        undefined,
        undefined,
        mockExecutor
      );
      const res = await orchestrator.chat("Tell me about Tirupati");

      expect(res.intent).toBe("destination_information");
      expect(res.summary).toBe("Custom plan generated by mock AI");
      expect(mockProvider.generateStructuredResponse).toHaveBeenCalled();
    });

    it("should not fabricate safetyScore if not present in context data", async () => {
      const provider = new DeterministicAIProvider();
      const mockPrompt = `Verified Context Data:
\`\`\`json
{
  "intent": "trip_planning",
  "destination": { "name": "Araku" },
  "safety": { "overview": "Safe destination" }
}
\`\`\``;
      const result = await provider.generateStructuredResponse<OrchestratorResponseDto>(mockPrompt);
      expect(result.safety?.safetyScore).toBeUndefined();
    });
  });

  describe("6B: Intent & Entity Classification", () => {
    const classifier = new IntentClassifier();

    it("should classify trip planning intent and extract days, destination, and parents group", () => {
      const result = classifier.classify("Plan a 2-day trip to Araku for my parents");
      expect(result.intent).toBe("trip_planning");
      expect(result.entities.days).toBe(2);
      expect(result.entities.destinationName).toBe("Araku");
      expect(result.entities.travellerGroup).toBe("parents");
      expect(result.requiredTools).toContain("destination_search");
      expect(result.requiredTools).toContain("elderly_support");
    });

    it("should dynamically select accessibility tool when wheelchair is mentioned in trip planning", () => {
      const result = classifier.classify("Plan a 3-day trip to Goa with wheelchair access");
      expect(result.intent).toBe("trip_planning");
      expect(result.requiredTools).toContain("accessibility");
    });

    it("should dynamically select local_businesses tool when food or stay is mentioned", () => {
      const result = classifier.classify(
        "Plan a 2-day holiday in Jaipur with best hotels and food"
      );
      expect(result.intent).toBe("trip_planning");
      expect(result.requiredTools).toContain("local_businesses");
    });

    it("should classify weather query intent", () => {
      const result = classifier.classify("What is the weather forecast and rain in Coorg?");
      expect(result.intent).toBe("weather_query");
      expect(result.entities.destinationName).toBe("Coorg");
      expect(result.requiredTools).toContain("weather");
    });

    it("should classify safety query intent", () => {
      const result = classifier.classify("Is Tirupati safe to travel at night?");
      expect(result.intent).toBe("safety_query");
      expect(result.entities.destinationName).toBe("Tirupati");
      expect(result.requiredTools).toContain("safety");
    });

    it("should classify women safety query intent", () => {
      const result = classifier.classify("What are the women safety helplines in Delhi?");
      expect(result.intent).toBe("women_safety_query");
      expect(result.requiredTools).toContain("safety");
      expect(result.requiredTools).toContain("emergency_resources");
    });

    it("should classify route query intent", () => {
      const result = classifier.classify("How to reach Varanasi and what is the driving route?");
      expect(result.intent).toBe("route_query");
      expect(result.requiredTools).toContain("routing");
    });

    it("should classify accessibility query intent", () => {
      const result = classifier.classify(
        "Is Borra Caves wheelchair accessible for disabled visitors?"
      );
      expect(result.intent).toBe("accessibility_query");
      expect(result.requiredTools).toContain("accessibility");
    });

    it("should classify translation query intent", () => {
      const result = classifier.classify("Translate hello to hindi");
      expect(result.intent).toBe("translation_query");
      expect(result.requiredTools).toContain("translation");
    });

    it("should fallback to general tourism query for ambiguous input", () => {
      const result = classifier.classify("Tell me something interesting about travelling");
      expect(result.intent).toBe("general_tourism_query");
    });
  });

  describe("6C: Tool Registry & Safe Execution Engine", () => {
    it("should maintain all 25 predefined controlled tools in the registry", () => {
      expect(Object.keys(TOOL_REGISTRY).length).toBe(25);
      expect(TOOL_REGISTRY.destination_search.requiresAuth).toBe(false);
      expect(TOOL_REGISTRY.crowd_intelligence.requiresAuth).toBe(false);
      expect(TOOL_REGISTRY.women_safety_intelligence.requiresAuth).toBe(false);
      expect(TOOL_REGISTRY.accessibility_intelligence.requiresAuth).toBe(false);
      expect(TOOL_REGISTRY.elderly_travel_intelligence.requiresAuth).toBe(false);
      expect(TOOL_REGISTRY.budget_intelligence.requiresAuth).toBe(false);
      expect(TOOL_REGISTRY.experience_intelligence.requiresAuth).toBe(false);
      expect(TOOL_REGISTRY.content_intelligence.requiresAuth).toBe(false);
      expect(TOOL_REGISTRY.local_business_intelligence.requiresAuth).toBe(false);
      expect(TOOL_REGISTRY.user_preferences.requiresAuth).toBe(true);
      expect(TOOL_REGISTRY.weather.category).toBe("realtime");
    });

    it("should skip user-private tools when unauthenticated", async () => {
      const executor = new ToolExecutor();
      const context = await executor.executeTools(["user_preferences", "user_trips"], {});
      expect(context.user_preferences).toBeUndefined();
      expect(context.user_trips).toBeUndefined();
    });

    it("should execute user tools when authenticated", async () => {
      const mockPrefService = {
        getPreferences: vi.fn().mockResolvedValue({
          interests: ["nature", "temples"],
          travelStyle: "family"
        })
      } as unknown as PreferencesService;

      const executor = new ToolExecutor(
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        mockPrefService
      );

      const mockUser: AuthenticatedUser = {
        id: "11111111-1111-1111-1111-111111111111",
        email: "tourist@test.com",
        roles: ["tourist"],
        isAnonymous: false
      };

      const context = await executor.executeTools(["user_preferences"], {}, mockUser);
      expect(context.user_preferences).toBeDefined();
      expect(context.sources.some((s) => s.resource === "travel_preferences")).toBe(true);
    });

    it("should isolate individual tool failures without crashing", async () => {
      const mockWeatherService = {
        getDestinationWeather: vi.fn().mockRejectedValue(new Error("External weather down"))
      } as unknown as WeatherService;

      const mockTourService = {
        getDestinations: vi.fn().mockResolvedValue({
          destinations: [{ id: "02cdfbc0-98c3-46b0-a288-a619aa93ced2", name: "Tirupati" }]
        })
      } as unknown as TourismService;

      const executor = new ToolExecutor(mockTourService, mockWeatherService);

      const context = await executor.executeTools(["destination_search", "weather"], {
        destinationName: "Tirupati"
      });

      expect(context.destination).toBeDefined();
      expect(context.weather).toBeUndefined(); // Failed tool safely omitted
      expect(context.sources.some((s) => s.resource === "destinations")).toBe(true);
    });
  });

  describe("API Endpoint Security & Orchestrator Flow: POST /api/v1/ai/chat", () => {
    it("should return 400 if message is empty", async () => {
      const response = await request(app).post("/api/v1/ai/chat").send({ message: "" });
      expect(response.status).toBe(400);
      expect(response.body.error.code).toBe("BAD_REQUEST");
    });

    it("should return 400 if message exceeds 2000 characters", async () => {
      const huge = "A".repeat(2001);
      const response = await request(app).post("/api/v1/ai/chat").send({ message: huge });
      expect(response.status).toBe(400);
      expect(response.body.error.message).toContain(
        "exceeds maximum allowed length of 2000 characters"
      );
    });

    it("should successfully process unauthenticated trip planning query", async () => {
      const response = await request(app)
        .post("/api/v1/ai/chat")
        .send({ message: "Plan a 2-day trip to Araku for my parents" });

      expect(response.status).toBe(200);
      expect(response.body.success).toBe(true);
      expect(response.body.data.intent).toBe("trip_planning");
      expect(response.body.data.summary).toBeDefined();
      expect(Array.isArray(response.body.data.recommendations)).toBe(true);
      expect(Array.isArray(response.body.data.sources)).toBe(true);
    }, 30000);

    it("should process safety query and return verified sources", async () => {
      const response = await request(app)
        .post("/api/v1/ai/chat")
        .send({ message: "What are the women safety helplines in Delhi?" });

      expect(response.status).toBe(200);
      expect(response.body.success).toBe(true);
      expect(response.body.data.intent).toBe("women_safety_query");
      expect(response.body.data.sources).toBeDefined();
    }, 30000);
  });
});
